---
- name: setup database virtual machine with nginx/php
  hosts: client
  become: true

  tasks:
    - name: Install docker dependencies
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        update_cache: true

    - name: add Dockers GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg

    - name: add Dockers repo
      apt_repository:
        repo: deb https://download.docker.com/linux/debian bookworm stable

    - name: install docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
        update_cache: true
